#!/usr/bin/env bash

curl https://raw.githubusercontent.com/james-turner/aws-mfa/master/mfa_login -o $HOME/.aws/mfa_login

FILE=$HOME/.aws-mfa
cat > $FILE <<- EOM
#!/usr/bin/env bash

# override to facilitate sts login if required
aws(){
  NOW="$(date +%s)"
  if [[ ! -e "$HOME/.aws_sts_credentials" || "$NOW" > "$AWS_SESSION_EXPIRATION" ]]; then
    $HOME/.aws/mfa_login
  fi
  source $HOME/.aws_sts_credentials
  /usr/local/bin/aws "$@";
}
EOM

echo "source ~/.aws-mfa" >> ~/.bash_profile
